### ISSUE TITLE
Can't build; biojava.org is down.

### ISSUE THREAD

**Issue by mycrobe** [biojava/rcsb-sequenceviewer#3]
Is this a temporary or permanent thing?

**Comment by josemduarte** [comment]
I don't know why biojava.org is down, but in any case I don't think you need biojava.org in order to build this. All that's needed is maven central where the artifacts (jar files) are stored.

**Comment by mycrobe** [comment]
I apologize for not providing a sane error message: The build was failing while attempting to locate artifact `javaws:javaws:jar:1.0` from biojava.org's maven repo.

I find this very strange, since it's part of the JRE. 

biojava.org is now up, and I was able to build this morning. I note that I have `javaws` installed both as an external dependency *and* as part of the JDK.

Notably, the external dependency version has *RCSB-PDB* public key and signature file.

**Comment by andreasprlic** [comment]
Hi, I am out on paternity leave. I can take a look at this when I am back. Andreas

**Comment by andreasprlic** [comment]
new repository is at 

```xml
<repository>
    <id>biojava-legacy-repo</id>
    <name>BioJava's Git based legacy maven repo</name>
    <url>https://github.com/biojava/maven-repo/raw/master/</url>
</repository>
```

see also https://github.com/biojava/biojava/issues/451
